# This is a basic workflow to help you get started with Actions
name: 'Notebook-To-Py'
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9.7
      - name: Install required packages
        run: "pip install numpy scipy matplotlib jupyter"

      - name: (create folder if not present)
        run:  "mkdir -p ${GITHUB_WORKSPACE}/pys"
        
      - name: Clear old scripts
        run: "rm -rf ${GITHUB_WORKSPACE}/pys/*"
#      - name: Run notebooks
#        run: "jupyter run ${GITHUB_WORKSPACE}/notebooks/*.ipynb"
      - name: Export notebooks
        run: "jupyter nbconvert --to python ${GITHUB_WORKSPACE}/notebooks/*"
        
      - name: Copy scripts
        run: "cp  ${GITHUB_WORKSPACE}/notebooks/*.py  ${GITHUB_WORKSPACE}/pys/"
    
      - name: Push to repo
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -A
          git commit -m "Actions: generated scripts"
          git push origin master
